export default keyMap = {
  EN: "EN",
  VI: "VI",
  MALE: "MALE",
  FEMALE: "FEMALE",
  MUANGAY: "MUANGAY",
  THEMNGAY: "THEMNGAY",
  CHOXACNHAN: "CHOXACNHAN",
  CHOLAYHANG: "CHOLAYHANG",
  DANGGIAO: "DANGGIAO",
  DANHGIA: "DANHGIA",
  DAMUA: "DAMUA",
  HUYDON: "HUYDON",
  TRONGGIO: "TRONGGIO",
  CHOXACNHAN_DATHANHTOAN: "CHOXACNHAN_DATHANHTOAN",
  CHOXACNHAN_CHUATHANHTOAN: "CHOXACNHAN_CHUATHANHTOAN",
  CHOLAYHANG_DATHANHTOAN: "CHOLAYHANG_DATHANHTOAN",
  CHOLAYHANG_CHUATHANHTOAN: "CHOLAYHANG_CHUATHANHTOAN",
  DANGSHIP_DATHANHTOAN: "DANGSHIP_DATHANHTOAN",
  DANGSHIP_CHUATHANHTOAN: "DANGSHIP_CHUATHANHTOAN",
  VANCHUYEN: "VANCHUYEN",
  GIAMGIA: "GIAMGIA",
  VOUCHERSHOP: "VOUCHERSHOP",
};

export const notifyTitleId = {
  GIAO_HANG_THANH_CONG: "GIAO_HANG_THANH_CONG",
  DON_HANG_DUOC_XAC_NHAN: "DON_HANG_DUOC_XAC_NHAN",
  DON_HANG_DANG_DUOC_GIAO: "DON_HANG_DANG_DUOC_GIAO",
  DON_HANG_BI_HUY: "DON_HANG_BI_HUY",
  HE_THONG: "HE_THONG",
}

export const roleId = {
  ADMIN: "ADMIN",
  USER: "USER",
  SUPPLIER: "SUPPLIER",
}