export default keyMap = {
  EN: "EN",
  VI: "VI",
  TRONGGIO: "TRONGGIO",
  CHOLAYHANG_DATHANHTOAN: "CHOLAYHANG_DATHANHTOAN",
  CHOLAYHANG_CHUATHANHTOAN: "CHOLAYHANG_CHUATHANHTOAN",
  DANGSHIP_DATHANHTOAN: "DANGSHIP_DATHANHTOAN",
  DANGSHIP_CHUATHANHTOAN: "DANGSHIP_CHUATHANHTOAN"
};
