export default namePage = {
  HOME: "Home",
  INFORMATION: "Information",
  PRODUCTDETAILS: "Productdetails",
  IDENTITY: "Identity",
  SETTING: "Setting",
  SETPROFILE: "Setprofile",
  CART: "Cart",
  REGISTER: "Register",
  REGISTER_INFORMATION: "RegisterInformation",
  CHAT: "Chat",
  MESS: "Mess",
  LOGIN: "Login",
  FORGOT_PASSWORD: "Forgot_password",
  VERIFICATION: "Verification",
  RESET: "Reset",
  MODAL: "Modal",
  PAY: "Pay",
  PAYMETHOD: "Paymethod",
  CHOOSEBANK: "Choosebank",
  AGENCY: "Agency",
  SHIPPER: "Shipper",
  ALLEVA: "AllEva",
  EVALUATE: "Evaluate",
  SHOP: "Shop",
  PRODUCTDETAILS: "ProductDetails",
  RECOMMEN: "Recommen",
};
