export default namePage = {
  HOME: "Home",
  INFORMATION: "Information",
  IDENTITY: "Identity",
  SETTING: "Setting",
  SETPROFILE: "Setprofile",
  CART: "Cart",
  REGISTER: "Register",
  REGISTER_INFORMATION: "RegisterInformation",
  CHAT: "Chat",
  MESS: "Mess",
  LOGIN: "Login",
  FORGOT_PASSWORD: "Forgot_password",
  VERIFICATION: "Verification",
  RESET: "Reset",
};
